# Generated by Django 3.0 on 2020-09-21 01:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200916_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
